version: 0.2
env:
  variables:
    ECR_REPO: 339712871948.dkr.ecr.us-east-1.amazonaws.com/catalog
    ECR_REGION: us-east-1
    CONTAINER_NAME: lks-catalog-container
phases:
  install:
    runtime-versions:
      nodejs: 16
      docker: 20
  pre_build:
    commands:
      - echo "Login to ECR"
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $ECR_REPO:latest .
      - docker tag $ECR_REPO:latest $ECR_REPO:$(date +%Y%m%d%H%M%S)
  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $ECR_REPO:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME ${ECR_REPO}:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
